name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Chequea el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura las credenciales de AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    # 3. Login en Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 4. Construir la imagen de Docker
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.prod -t ${{ vars.ECR_REPOSITORY_URI }}:latest .

    # 5. Subir la imagen a ECR
    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ vars.ECR_REPOSITORY_URI }}:latest
